### ISSUE TITLE
DELIVERABLE - Search page for movies, should include streaming service availabilty

### ISSUE THREAD

**Issue by ciaraugasmoy** [ciaraugasmoy/WhatToWatch#6]
browse / search page where users can view available movies and tv shows.  Should include where they can watch it
- database to store movie and movie info, inclusive of streaming info
- function to call api given user query
- function to store movie data from api call in db, cache

**Comment by rerciyas** [comment]
.

**Comment by ciaraugasmoy** [comment]
back end done - search with pagination

to do - front end queries with pagination
to do - singular movie detail query

**Comment by ciaraugasmoy** [comment]
watch providers now included on movie page, showing user provider separate
